project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!tmp/**"

website:
  search: false
  title: "Haiyang Zhang"
  site-url: "https://haiyangzhang.com"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
      - href: cv/index.qmd
        text: CV
      - href: flying/index.qmd
        text: Flying
  page-footer:
    left: "Copyright 2026 Haiyang Zhang"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    anchor-sections: true
    smooth-scroll: true

execute:
  freeze: auto
